language: python
python:
  - "3.6"
  - "3.7"
before_install:
  - pip install -r requirements.txt
  - python3 -m pip install git+https://github.com/mnick/scikit-tensor.git
install:
  - pip --version
script:
  - pytest --pyargs tests