language: python

os: linux
dist: xenial
sudo: true
addons:
   apt:
     sources:
        - ubuntu-toolchain-r-test
     packages:
        - cmake-data
        - cmake
        - g++-7
        - libpython3-dev
        - python3-numpy
#python:
#  - "3.5"
before_script:
  - wget https://bootstrap.pypa.io/get-pip.py
  - python3 --version
  - sudo python3 get-pip.py
  - pip3 --version
  - pip3 install -r requirements.txt
  - python3 -m pip install git+https://github.com/mnick/scikit-tensor.git

script:
   # build C++ module
  - sudo update-alternatives --install /usr/bin/python python /usr/bin/python2.7 1
  - sudo update-alternatives --install /usr/bin/python python /usr/bin/python3.5 2
  - export CXX=g++-7
  - ${CXX} --version
  - cmake --version
  - python --version
  - git submodule update --init
  - cd cpp
  - mkdir build
  - cd build
  - cmake ..
  - make
  - sudo make install
  - cd ../..
  - python3 -m pytest tests