language: python

os: linux
dist: xenial
sudo: true
addons:
   apt:
     sources:
        - ubuntu-toolchain-r-test
     packages:
        - cmake-data
        - cmake
        - g++-7
        - libpython3-dev
        - python3-numpy
        - python3-numpy-dbg
        - python3-tk
        #- libeigen3-dev
        - libboost-python-dev
        - libboost-test-dev

before_install:
  - wget http://bitbucket.org/eigen/eigen/get/3.3.4.tar.bz2
  - mv 3.3.4.tar.bz2 eigen3.3.4.tar.bz2
  - tar -xvf eigen3.3.4.tar.bz2
  - rm eigen3.3.4.tar.bz2
  - mv eigen-eigen-* eigen
  - export Eigen3_ROOT=`pwd`/eigen
# have to use pre-installed python 3.5, specifying 3.5 installs a different version that has no headers and makes the
# cpp module build fail
#python:
#  - "3.5"
before_script:
  # set up eigen 3.4
  - wget https://bootstrap.pypa.io/get-pip.py
  - python3 --version
  - sudo -H python3 get-pip.py
  - python3 -m pip --version
  - python3 -m pip install -r requirements.txt
  # TODO: fix the bug in scikit-tensor installer (maybe?) to allow it to be added to requirements.txt for pip
  - python3 -m pip install git+https://github.com/mnick/scikit-tensor.git
  - mkdir -p ~/.config/matplotlib/
  - touch ~/.config/matplotlib/matplotlibrc
  - 'echo "backend : agg" > ~/.config/matplotlib/matplotlibrc'

script:
  # build C++ module
  - export CXX=g++-7
  - ${CXX} --version
  - cmake --version
  - git submodule update --init
  - cd cpp
  - mkdir build
  - cd build
  - cmake -DHUNTER_ENABLED=OFF -DEIGEN3_INCLUDE_DIR=${Eigen3_ROOT} ..
  - make
  - sudo make install
  - cd ../..
  # run python tests
  - python3 -m pytest tests

install:
  - echo "placeholder install script (to disable default)"